services:
  tw-stock-ml:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tw-stock-ml
    volumes:
      - ../logs:/app/logs
      - ../src:/app/src
      - ../tests:/app/tests
      - ../data:/app/data
      - ../model:/app/model
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=tw_stock_database
      - DB_USER=root
      - DB_PASSWORD=stock
      - DB_NAME=TWSE
    command: python src/main.py
    networks:
      - db_network

networks:
  db_network:
    external: true
